/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.image.BufferedImage;
import java.util.ArrayList;
import static lib.Tools.TABTOSPACE;
import java.util.HashMap;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import phones.Result;
import lib.Tools;

/**
 *
 * @author Woh
 */
public class DetailPhoneInfoPanel extends javax.swing.JPanel {

    /**
     * Creates new form DetailPhoneInfoPanel
     */
    public DetailPhoneInfoPanel() {
        initComponents();
    }
    
    public void setPhoneImage(Result result) {
        BufferedImage resize = Tools.resize(result.getBufferedImage(), 300);
        phoneImage.setIcon(new ImageIcon(resize));
    }
    
    public void addInformation(Result result) {
        DefaultListModel<String> dlm = new DefaultListModel<>();
        ArrayList<String> title = result.getMP().title;
        HashMap<String,ArrayList<String>> map = result.getMP().getInfo2();
        for(int i=0;i<title.size();i++) {
            String t = title.get(i);
            if(!map.get(t).isEmpty())
                dlm.addElement(t);
            for(String s:map.get(t)){
                s = TABTOSPACE(s);
                if(s.charAt(s.length()-1)==' ') s = s.substring(0,s.length()-3);
                String[] temp = s.split("\n");
                if(temp.length>1){
                    for(String o:temp){
                        dlm.addElement(o);
                    }
                }else dlm.addElement(s);
            }
            dlm.addElement(" ");
        }
        jList.setModel(dlm);
        jScrollPane.setViewportView(jList);
    }
    
    public void setup(Result result) {
        setPhoneImage(result);
        addInformation(result);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        phoneImage = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane(jList);
        jList = new javax.swing.JList<>();

        phoneImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        phoneImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smartphone-samsung-s8.jpg"))); // NOI18N

        jScrollPane.setViewportView(jList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(phoneImage, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(phoneImage, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
            .addComponent(jScrollPane)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> jList;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel phoneImage;
    // End of variables declaration//GEN-END:variables

}
