/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JCheckBox;
import javax.swing.JTextField;
import knowledge.Result;
import knowledge.SimpleInformation;

/**
 *
 * @author Woh
 */
public class FilterPanel extends javax.swing.JPanel {

    /**
     * Creates new form FilterPanel
     */
    public HashMap<String, JCheckBox> checkboxes;
    public HashMap<String, JTextField> textfields;
    public ArrayList<String> keyword;
    
    public FilterPanel() {
        initComponents();
        checkboxes = new HashMap<>();
        textfields = new HashMap<>();
        
        checkboxes.put("brand_samsung", brand_samsung);
        checkboxes.put("brand_apple", brand_apple);
        checkboxes.put("brand_sony", brand_sony);
        checkboxes.put("brand_xiaomi", brand_xiaomi);
        checkboxes.put("brand_huawei", brand_huawei);
        checkboxes.put("brand_asus", brand_asus);
        checkboxes.put("brand_oneplus", brand_oneplus);
        checkboxes.put("brand_htc", brand_htc);
        checkboxes.put("brand_nokia", brand_nokia);
        textfields.put("brand_other", brand_otherTextField);
        
        
    }

    public void showSearchResult(Result[] results) {
        displayInnerPanel.removeAll();
        for (Result result : results) {
            SimpleInformation si = result.getSimpleInformation();
            SimplePhoneInfoPanel spip = new SimplePhoneInfoPanel();
            spip.setup(si.brand, si.phoneName, si.price);
            displayInnerPanel.add(spip);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filterLabel = new javax.swing.JLabel();
        displayScrollPane = new javax.swing.JScrollPane();
        displayInnerPanel = new javax.swing.JPanel();
        simplePhoneInfoPanel1 = new gui.SimplePhoneInfoPanel();
        simplePhoneInfoPanel2 = new gui.SimplePhoneInfoPanel();
        simplePhoneInfoPanel3 = new gui.SimplePhoneInfoPanel();
        filterScrollPane = new javax.swing.JScrollPane();
        filterPanel = new javax.swing.JPanel();
        brandFilterLabel = new javax.swing.JLabel();
        brandFilterScrollPane = new javax.swing.JScrollPane();
        brandFilterPanel = new javax.swing.JPanel();
        brand_samsung = new javax.swing.JCheckBox();
        brand_apple = new javax.swing.JCheckBox();
        brand_sony = new javax.swing.JCheckBox();
        brand_xiaomi = new javax.swing.JCheckBox();
        brand_huawei = new javax.swing.JCheckBox();
        brand_asus = new javax.swing.JCheckBox();
        brand_oneplus = new javax.swing.JCheckBox();
        brand_htc = new javax.swing.JCheckBox();
        brand_nokia = new javax.swing.JCheckBox();
        brand_other = new javax.swing.JCheckBox();
        brand_otherTextField = new javax.swing.JTextField();
        priceFilterLabel = new javax.swing.JLabel();
        priceFilterPanel = new javax.swing.JPanel();
        priceFromLabel = new javax.swing.JLabel();
        priceFromTextField = new javax.swing.JTextField();
        priceToLabel = new javax.swing.JLabel();
        priceToTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        osFilterScrollPane = new javax.swing.JScrollPane();
        osFilterPanel = new javax.swing.JPanel();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jTextField3 = new javax.swing.JTextField();
        memoryFilterLabel = new javax.swing.JLabel();
        memoryFilterScrollPane = new javax.swing.JScrollPane();
        memoryFilterPanel = new javax.swing.JPanel();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jTextField4 = new javax.swing.JTextField();
        storageFilterLabel = new javax.swing.JLabel();
        storageFilterScrollPane = new javax.swing.JScrollPane();
        storageFilterPanel = new javax.swing.JPanel();
        jCheckBox23 = new javax.swing.JCheckBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        jCheckBox25 = new javax.swing.JCheckBox();
        jCheckBox26 = new javax.swing.JCheckBox();
        jCheckBox27 = new javax.swing.JCheckBox();
        jCheckBox28 = new javax.swing.JCheckBox();
        jCheckBox29 = new javax.swing.JCheckBox();
        jTextField5 = new javax.swing.JTextField();
        numberOfSimSlotsFilterLabel = new javax.swing.JLabel();
        numberOfSimSlotsFilterPanel = new javax.swing.JPanel();
        jCheckBox21 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        frontCameraFilterLabel = new javax.swing.JLabel();
        frontCameraFilterScrollPane = new javax.swing.JScrollPane();
        frontCameraFilterCamera = new javax.swing.JPanel();
        rearCameraFilterLabel = new javax.swing.JLabel();
        rearCameraFilterScrollPane = new javax.swing.JScrollPane();
        rearCameraFilterPanel = new javax.swing.JPanel();
        searchTextField = new javax.swing.JTextField();
        searchButtonTop = new javax.swing.JButton();

        filterLabel.setText("Filter");

        displayInnerPanel.setLayout(new java.awt.GridLayout(0, 1));
        displayInnerPanel.add(simplePhoneInfoPanel1);
        displayInnerPanel.add(simplePhoneInfoPanel2);
        displayInnerPanel.add(simplePhoneInfoPanel3);

        displayScrollPane.setViewportView(displayInnerPanel);

        filterScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        filterScrollPane.setMaximumSize(new java.awt.Dimension(325, 780));
        filterScrollPane.setMinimumSize(new java.awt.Dimension(325, 780));
        filterScrollPane.setName(""); // NOI18N
        filterScrollPane.setPreferredSize(new java.awt.Dimension(325, 780));

        filterPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        brandFilterLabel.setText("Brand");

        brandFilterScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        brand_samsung.setText("Samsung");

        brand_apple.setText("Apple");
        brand_apple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brand_appleActionPerformed(evt);
            }
        });

        brand_sony.setText("Sony");

        brand_xiaomi.setText("XiaoMi");

        brand_huawei.setText("HuaWei");

        brand_asus.setText("Asus");

        brand_oneplus.setText("OnePlus");

        brand_htc.setText("HTC");
        brand_htc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brand_htcActionPerformed(evt);
            }
        });

        brand_nokia.setText("Nokia");

        brand_other.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brand_otherActionPerformed(evt);
            }
        });

        brand_otherTextField.setText("Other");

        javax.swing.GroupLayout brandFilterPanelLayout = new javax.swing.GroupLayout(brandFilterPanel);
        brandFilterPanel.setLayout(brandFilterPanelLayout);
        brandFilterPanelLayout.setHorizontalGroup(
            brandFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brandFilterPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(brandFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(brandFilterPanelLayout.createSequentialGroup()
                        .addComponent(brand_other)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(brand_otherTextField))
                    .addGroup(brandFilterPanelLayout.createSequentialGroup()
                        .addGroup(brandFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(brand_samsung)
                            .addComponent(brand_apple)
                            .addComponent(brand_sony)
                            .addComponent(brand_xiaomi)
                            .addComponent(brand_huawei)
                            .addComponent(brand_asus)
                            .addComponent(brand_oneplus)
                            .addComponent(brand_htc)
                            .addComponent(brand_nokia))
                        .addGap(0, 173, Short.MAX_VALUE)))
                .addContainerGap())
        );
        brandFilterPanelLayout.setVerticalGroup(
            brandFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brandFilterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(brand_samsung)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(brand_apple)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(brand_sony)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(brand_xiaomi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(brand_huawei)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(brand_asus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(brand_oneplus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(brand_htc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(brand_nokia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(brandFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(brand_other)
                    .addComponent(brand_otherTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        brandFilterScrollPane.setViewportView(brandFilterPanel);

        priceFilterLabel.setText("Price");

        priceFromLabel.setText("from");

        priceFromTextField.setText("123");
        priceFromTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceFromTextFieldActionPerformed(evt);
            }
        });

        priceToLabel.setText("to");

        priceToTextField.setText("456");

        javax.swing.GroupLayout priceFilterPanelLayout = new javax.swing.GroupLayout(priceFilterPanel);
        priceFilterPanel.setLayout(priceFilterPanelLayout);
        priceFilterPanelLayout.setHorizontalGroup(
            priceFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(priceFilterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(priceFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, priceFilterPanelLayout.createSequentialGroup()
                        .addComponent(priceFromLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(priceFilterPanelLayout.createSequentialGroup()
                        .addComponent(priceToLabel)
                        .addGap(21, 21, 21)))
                .addGroup(priceFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(priceFromTextField)
                    .addComponent(priceToTextField))
                .addContainerGap())
        );
        priceFilterPanelLayout.setVerticalGroup(
            priceFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(priceFilterPanelLayout.createSequentialGroup()
                .addGroup(priceFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceFromLabel)
                    .addComponent(priceFromTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(priceFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceToLabel)
                    .addComponent(priceToTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel2.setText("Operating System");

        jCheckBox11.setText("Android");

        jCheckBox12.setText("iOS");

        jCheckBox13.setText("Window Phone");

        jCheckBox14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout osFilterPanelLayout = new javax.swing.GroupLayout(osFilterPanel);
        osFilterPanel.setLayout(osFilterPanelLayout);
        osFilterPanelLayout.setHorizontalGroup(
            osFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(osFilterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(osFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckBox11)
                    .addComponent(jCheckBox12)
                    .addComponent(jCheckBox13)
                    .addGroup(osFilterPanelLayout.createSequentialGroup()
                        .addComponent(jCheckBox14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        osFilterPanelLayout.setVerticalGroup(
            osFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(osFilterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(osFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox14)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        osFilterScrollPane.setViewportView(osFilterPanel);

        memoryFilterLabel.setText("Memory");

        jCheckBox15.setText("256MB");
        jCheckBox15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox15ActionPerformed(evt);
            }
        });

        jCheckBox16.setText("512MB");

        jCheckBox17.setText("1GB");

        jCheckBox18.setText("2GB");

        jCheckBox19.setText("3GB");

        jCheckBox20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox20ActionPerformed(evt);
            }
        });

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout memoryFilterPanelLayout = new javax.swing.GroupLayout(memoryFilterPanel);
        memoryFilterPanel.setLayout(memoryFilterPanelLayout);
        memoryFilterPanelLayout.setHorizontalGroup(
            memoryFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memoryFilterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(memoryFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(memoryFilterPanelLayout.createSequentialGroup()
                        .addComponent(jCheckBox20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4))
                    .addGroup(memoryFilterPanelLayout.createSequentialGroup()
                        .addGroup(memoryFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox15)
                            .addComponent(jCheckBox16)
                            .addComponent(jCheckBox17)
                            .addComponent(jCheckBox18)
                            .addComponent(jCheckBox19))
                        .addGap(0, 189, Short.MAX_VALUE)))
                .addContainerGap())
        );
        memoryFilterPanelLayout.setVerticalGroup(
            memoryFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memoryFilterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(memoryFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox20)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        memoryFilterScrollPane.setViewportView(memoryFilterPanel);

        storageFilterLabel.setText("Storage");

        jCheckBox23.setText("4GB");

        jCheckBox24.setText("8GB");

        jCheckBox25.setText("16GB");

        jCheckBox26.setText("32GB");

        jCheckBox27.setText("64GB");

        jCheckBox28.setText("128GB");

        javax.swing.GroupLayout storageFilterPanelLayout = new javax.swing.GroupLayout(storageFilterPanel);
        storageFilterPanel.setLayout(storageFilterPanelLayout);
        storageFilterPanelLayout.setHorizontalGroup(
            storageFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(storageFilterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(storageFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox23)
                    .addComponent(jCheckBox24)
                    .addComponent(jCheckBox25)
                    .addComponent(jCheckBox26)
                    .addComponent(jCheckBox27)
                    .addComponent(jCheckBox28)
                    .addGroup(storageFilterPanelLayout.createSequentialGroup()
                        .addComponent(jCheckBox29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        storageFilterPanelLayout.setVerticalGroup(
            storageFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(storageFilterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(storageFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox29)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        storageFilterScrollPane.setViewportView(storageFilterPanel);

        numberOfSimSlotsFilterLabel.setText("Number of Sim Slots");

        jCheckBox21.setText("1");

        jCheckBox22.setText("2");

        javax.swing.GroupLayout numberOfSimSlotsFilterPanelLayout = new javax.swing.GroupLayout(numberOfSimSlotsFilterPanel);
        numberOfSimSlotsFilterPanel.setLayout(numberOfSimSlotsFilterPanelLayout);
        numberOfSimSlotsFilterPanelLayout.setHorizontalGroup(
            numberOfSimSlotsFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(numberOfSimSlotsFilterPanelLayout.createSequentialGroup()
                .addGroup(numberOfSimSlotsFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox21)
                    .addComponent(jCheckBox22))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        numberOfSimSlotsFilterPanelLayout.setVerticalGroup(
            numberOfSimSlotsFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(numberOfSimSlotsFilterPanelLayout.createSequentialGroup()
                .addComponent(jCheckBox21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCheckBox22))
        );

        frontCameraFilterLabel.setText("Front camera");

        javax.swing.GroupLayout frontCameraFilterCameraLayout = new javax.swing.GroupLayout(frontCameraFilterCamera);
        frontCameraFilterCamera.setLayout(frontCameraFilterCameraLayout);
        frontCameraFilterCameraLayout.setHorizontalGroup(
            frontCameraFilterCameraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );
        frontCameraFilterCameraLayout.setVerticalGroup(
            frontCameraFilterCameraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        frontCameraFilterScrollPane.setViewportView(frontCameraFilterCamera);

        rearCameraFilterLabel.setText("Rear camera");

        javax.swing.GroupLayout rearCameraFilterPanelLayout = new javax.swing.GroupLayout(rearCameraFilterPanel);
        rearCameraFilterPanel.setLayout(rearCameraFilterPanelLayout);
        rearCameraFilterPanelLayout.setHorizontalGroup(
            rearCameraFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );
        rearCameraFilterPanelLayout.setVerticalGroup(
            rearCameraFilterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        rearCameraFilterScrollPane.setViewportView(rearCameraFilterPanel);

        javax.swing.GroupLayout filterPanelLayout = new javax.swing.GroupLayout(filterPanel);
        filterPanel.setLayout(filterPanelLayout);
        filterPanelLayout.setHorizontalGroup(
            filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numberOfSimSlotsFilterPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(priceFilterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(osFilterScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(brandFilterScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                    .addComponent(memoryFilterScrollPane)
                    .addComponent(storageFilterScrollPane)
                    .addComponent(frontCameraFilterScrollPane)
                    .addGroup(filterPanelLayout.createSequentialGroup()
                        .addGroup(filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(brandFilterLabel)
                            .addComponent(priceFilterLabel)
                            .addComponent(jLabel2)
                            .addComponent(memoryFilterLabel)
                            .addComponent(storageFilterLabel)
                            .addComponent(numberOfSimSlotsFilterLabel)
                            .addComponent(frontCameraFilterLabel)
                            .addComponent(rearCameraFilterLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(rearCameraFilterScrollPane))
                .addContainerGap())
        );
        filterPanelLayout.setVerticalGroup(
            filterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(brandFilterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(brandFilterScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceFilterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceFilterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(osFilterScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(memoryFilterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(memoryFilterScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(storageFilterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(storageFilterScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numberOfSimSlotsFilterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numberOfSimSlotsFilterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(frontCameraFilterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(frontCameraFilterScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rearCameraFilterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rearCameraFilterScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        filterScrollPane.setViewportView(filterPanel);

        searchButtonTop.setText("Search");
        searchButtonTop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonTopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filterScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchButtonTop))
                    .addComponent(displayScrollPane))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filterLabel)
                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButtonTop))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filterScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(displayScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jCheckBox20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox20ActionPerformed

    private void jCheckBox15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox15ActionPerformed

    private void jCheckBox14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox14ActionPerformed

    private void priceFromTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceFromTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceFromTextFieldActionPerformed

    private void brand_htcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brand_htcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brand_htcActionPerformed

    private void brand_otherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brand_otherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brand_otherActionPerformed

    private void brand_appleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brand_appleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brand_appleActionPerformed

    private void searchButtonTopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonTopActionPerformed
        // TODO add your handling code here:
//        Result[] results = API.search(keywords);
    }//GEN-LAST:event_searchButtonTopActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel brandFilterLabel;
    private javax.swing.JPanel brandFilterPanel;
    private javax.swing.JScrollPane brandFilterScrollPane;
    private javax.swing.JCheckBox brand_apple;
    private javax.swing.JCheckBox brand_asus;
    private javax.swing.JCheckBox brand_htc;
    private javax.swing.JCheckBox brand_huawei;
    private javax.swing.JCheckBox brand_nokia;
    private javax.swing.JCheckBox brand_oneplus;
    private javax.swing.JCheckBox brand_other;
    private javax.swing.JTextField brand_otherTextField;
    private javax.swing.JCheckBox brand_samsung;
    private javax.swing.JCheckBox brand_sony;
    private javax.swing.JCheckBox brand_xiaomi;
    private javax.swing.JPanel displayInnerPanel;
    private javax.swing.JScrollPane displayScrollPane;
    private javax.swing.JLabel filterLabel;
    private javax.swing.JPanel filterPanel;
    private javax.swing.JScrollPane filterScrollPane;
    private javax.swing.JPanel frontCameraFilterCamera;
    private javax.swing.JLabel frontCameraFilterLabel;
    private javax.swing.JScrollPane frontCameraFilterScrollPane;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox25;
    private javax.swing.JCheckBox jCheckBox26;
    private javax.swing.JCheckBox jCheckBox27;
    private javax.swing.JCheckBox jCheckBox28;
    private javax.swing.JCheckBox jCheckBox29;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel memoryFilterLabel;
    private javax.swing.JPanel memoryFilterPanel;
    private javax.swing.JScrollPane memoryFilterScrollPane;
    private javax.swing.JLabel numberOfSimSlotsFilterLabel;
    private javax.swing.JPanel numberOfSimSlotsFilterPanel;
    private javax.swing.JPanel osFilterPanel;
    private javax.swing.JScrollPane osFilterScrollPane;
    private javax.swing.JLabel priceFilterLabel;
    private javax.swing.JPanel priceFilterPanel;
    private javax.swing.JLabel priceFromLabel;
    private javax.swing.JTextField priceFromTextField;
    private javax.swing.JLabel priceToLabel;
    private javax.swing.JTextField priceToTextField;
    private javax.swing.JLabel rearCameraFilterLabel;
    private javax.swing.JPanel rearCameraFilterPanel;
    private javax.swing.JScrollPane rearCameraFilterScrollPane;
    private javax.swing.JButton searchButtonTop;
    private javax.swing.JTextField searchTextField;
    private gui.SimplePhoneInfoPanel simplePhoneInfoPanel1;
    private gui.SimplePhoneInfoPanel simplePhoneInfoPanel2;
    private gui.SimplePhoneInfoPanel simplePhoneInfoPanel3;
    private javax.swing.JLabel storageFilterLabel;
    private javax.swing.JPanel storageFilterPanel;
    private javax.swing.JScrollPane storageFilterScrollPane;
    // End of variables declaration//GEN-END:variables
}
