/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JLabel;
import knowledge.Information;
import knowledge.Result;

/**
 *
 * @author Woh
 */
public class SingleInformationPanel extends javax.swing.JPanel {
    /**
     * Creates new form SingleInformationPanel
     * @param informations
     */
    public SingleInformationPanel() {
        initComponents();
    }
    
    public void setup(Result result, String title) {
        addSetTitle(title);
        /**
         * so here we can get a hash map of "title"
         * for example:
         * i want to get "Network" information
         * title is "Network"
         * 
         * so Information[] informations = result.getInformations(title);
         * for each information, addSingleInformation(information)
         * 
         * information in "Network" should be like this:
         * Technology: GSM / CDMA / HSPA / EVDO / LTE
         * 
         * information in Launch should be like this:
         * informations[0] is Announced: 2016, October
         * informations[1] is Status: Available. Released 2016, October
         */
    }
    
    public void addSetTitle(String title) {
        removeAll();
        add(new JLabel(title));
    }
    
    public void addSingleInformation(Information information) {
        String conc = information.getLabel()+": "+information.getInformation();
        add(new JLabel(conc));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new java.awt.GridLayout(0, 1));

        jLabel1.setText("Network");
        add(jLabel1);

        jLabel2.setText("Technology: GSM / CDMA / HSPA / EVDO / LTE");
        add(jLabel2);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
